# Generated by Django 5.0.6 on 2024-07-30 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='imgUrl',
            field=models.TextField(default='', max_length=256),
            preserve_default=False,
        ),
    ]
