import type { Metadata } from "next";

import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import {CartProvider} from "@/utils/CartContext";
import React from "react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa">
      <body className=''>
        <CartProvider>
          <Header />
          {children}
          <ToastContainer position={"bottom-left"} className='text-right font-[Vazir]' rtl={true} />
          <Footer />
        </CartProvider>
      </body>
    </html>
  );
}
